services:
  postgres:
    image: postgres:16
    container_name: investment-risk-postgres
    environment:
      POSTGRES_USER: risk_user
      POSTGRES_PASSWORD: risk_password
      POSTGRES_DB: risk_analytics
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: